### ISSUE TITLE
Add explore view for voila schema

### ISSUE THREAD

**Issue by RoteKekse** [nomad-hzb/nomad-baseclasses#11]
Please add an explore view for voila schema. Add sth like below to your `nomad.yaml` file

```
ui:
  unit_systems:
    selected: 'my_units'
    options:
      my_units:
        label: 'my_units'
        units:
          current:
             definition: 'mA'
          length:
            definition: 'cm'
  apps:
    # Configures which apps to show. Note that the app for 'entries' (which
    # corresponds to searching all entries) has to be included at the moment.
                #- 'data.name#baseclasses.chemical_energy.voltammetry.Voltammetry'
                #- 'data.voltage_shift#baseclasses.chemical_energy.voltammetry.Voltammetry'
                #- 'data.resistance#baseclasses.chemical_energy.voltammetry.Voltammetry'
    include:
      - 'eln'
      - 'solarcells'
      - 'entries'
      - 'voltammetry'
      - 'environments'
      - 'nkdata'
    # Configures a new app for samples
    options:
      nkdata:
        # Label of the App
        label: 'NK Data'
        # Path used in the URL, must be unique
        path: 'nkdata'
        # Used to categorize apps in the explore menu
        category: 'Experiment'
        # Brief description used in the app menu
        description: 'An app customized for NK Data.'
        # Longer description that can also use markdown
        # Controls which columns are shown in the results table
        columns:
          selected:
            - 'entry_name'
            - 'data.chemical_composition_or_formulas#hysprint_s.HZB_NKData'
            - 'entry_create_time'
            - 'entry_type'
            - 'authors'
            - 'upload_name'
          options:
            entry_name:
              label: 'Name'
              align: 'left'
            results.material.elements:
              label: 'Elements'
              align: 'left'
            data.chemical_composition_or_formulas#hysprint_s.HZB_NKData:
              label: 'Elements and Formulas'
              align: 'left'
            results.material.chemical_formula_hill:
              label: 'Formula'
              align: 'left'
            entry_type:
              label: 'Entry type'
              align: 'left'
            upload_name:
              label: 'Upload name'
              align: 'left'
            upload_id:
              label: 'Upload id'
              align: 'left'
            upload_create_time:
              label: 'Upload time'
              align: 'left'
            entry_create_time:
              label: 'Entry time'
              align: 'left'
            authors:
              label: 'Authors'
              align: 'left'
        # Dictionary of search filters that are always enabled for queries made within
        # this app. This is especially important to narrow down the results to the
        # wanted subset. Any available search filter can be targeted here.
        filters:
          include:
            - '*#hysprint_s.HZB_NKData'
        filters_locked:
          section_defs.definition_qualified_name: 'hysprint_s.HZB_NKData'

        # Controls the filter menus shown on the left
        filter_menus:
          options:
            material:
              label: 'Material'
              level: 0
            elements:
              label: 'Elements / Formula'
              level: 1
              size: 'xl'
            eln:
              label: 'Electronic Lab Notebook'
              level: 0
            custom_quantities:
              label: 'User Defined Quantities'
              level: 0
              size: 'l'
            author:
              label: 'Author / Origin / Dataset'
              level: 0
              size: 'm'
            metadata:
              label: 'Visibility / IDs / Schema'
              level: 0
        dashboard:
          widgets:
            - type: 'periodictable'
              scale: 'linear'
              quantity: 'results.material.elements'
              layout:
                xxl:
                  minH: 3
                  minW: 3
                  h: 6
                  w: 12
                  y: 0
                  x: 6
                xl:
                  minH: 3
                  minW: 3
                  h: 6
                  w: 12
                  y: 0
                  x: 0
                lg:
                  minH: 3
                  minW: 3
                  h: 6
                  w: 12
                  y: 0
                  x: 6
                md:
                  minH: 3
                  minW: 3
                  h: 6
                  w: 12
                  y: 0
                  x: 6
                sm:
                  minH: 3
                  minW: 3
                  h: 6
                  w: 12
                  y: 0
                  x: 6
            - type: scatterplot
              autorange: true
              color: results.material.n_elements
              y: data.data.n_data.maximum#hysprint_s.HZB_NKData
              x: data.data.n_data.minimum#hysprint_s.HZB_NKData
              layout:
                xxl:
                  minH: 3
                  minW: 3
                  h: 6
                  w: 6
                  y: 0
                  x: 6
                xl:
                  minH: 3
                  minW: 3
                  h: 6
                  w: 6
                  y: 0
                  x: 0
                lg:
                  minH: 3
                  minW: 3
                  h: 6
                  w: 6
                  y: 0
                  x: 6
                md:
                  minH: 3
                  minW: 3
                  h: 6
                  w: 6
                  y: 0
                  x: 6
                sm:
                  minH: 3
                  minW: 3
                  h: 6
                  w: 6
                  y: 0
                  x: 6

```
